apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot-container
        image: your_dockerhub_username/chatbot:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
spec:
  selector:
    app: chatbot
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000       # internal service port
      targetPort: 5000 # container port
      nodePort: 30080  # external port on your nodes (choose 30000-32767)
